image: runpod/pytorch:2.4.0-py3.11-cuda12.1-devel-ubuntu22.04
containerDisk: 40
gpuCount: 1
ports:
  - port: 8000
    expose: true

env:
  HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
  HF_MODEL_NAME: ${HF_MODEL_NAME}

startCommand: >
  bash -c "git clone https://github.com/Artaccann/OSOL_backend.git &&
           cd OSOL_backend &&
           pip install -r requirements.txt &&
           bash start.sh"
