name: osol-serverless-endpoint
image: .
entrypoint: handler.handler
containerDisk: 10
gpu: true
gpuCount: 1
accelerator: A10G

env:
  HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
  HF_MODEL_NAME: Artaccann/OSOL_backend
