name: osol-serverless-endpoint
image: runpod/python:3.10-uv
containerDisk: 10
gpu: true
gpuCount: 1
accelerator: A10G

entrypoint: handler.handler

env:
  HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
  HF_MODEL_NAME: Artaccann/OSOL_backend
